[versions]
jackson = "2.21.1"
typesafeConfig = "1.4.5"
functionaljava = "5.0"
lombok = "1.18.42"
checkerframework = "3.53.1"
checkerQual = "3.53.1"
slf4j = "2.0.17"
testng = "7.12.0"
assertj = "3.27.7"
logback = "1.5.32"
palantirJavaFormat = "2.88.0"
spotlessPlugin = "8.2.1"
checkerFrameworkPlugin = "1.0.2"
freefairLombok = "9.2.0"

[libraries]
functionaljava = { module = "org.functionaljava:functionaljava", version.ref = "functionaljava" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-module-parameter-names = { module = "com.fasterxml.jackson.module:jackson-module-parameter-names" }
jackson-datatype-jsr310 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8" }
typesafe-config = { module = "com.typesafe:config", version.ref = "typesafeConfig" }
checker-qual = { module = "org.checkerframework:checker-qual", version.ref = "checkerQual" }
checker = { module = "org.checkerframework:checker", version.ref = "checkerframework" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
testng = { module = "org.testng:testng", version.ref = "testng" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

[plugins]
checkerFramework = { id = "org.checkerframework", version.ref = "checkerFrameworkPlugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotlessPlugin" }
freefairLombok = { id = "io.freefair.lombok", version.ref = "freefairLombok" }
